version: '3.9'
services:
  app:
    ports:
      - 3000:3000
    build:
      context: frontend
    tty: true # コンテナを起動しっぱなしにする。
    volumes:
      - ./frontend:/app # フォルダを同期
      - node_modules:/app/node_modules # node_modules, .nextはボリュームに保存
      - next_data:/app/.next
    environment:
      - WATCHPACK_POLLING=true # ホットリロード（同期に必要）
    command: 'yarn dev'
    depends_on: # db必須のフロント, dbコンテナが先に立つ
      - db
  db:
    image: 'mysql:latest'
    expose:
      - 3306 # 他コンテナからアクセスできるポート番号
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
  node_modules:
  next_data:
