import Head from 'next/head'
import Link from 'next/link'
import { FC, ReactNode } from 'react'

import { BreadCrumbs, type Item as breadCrumbsitem } from './BreadCrumbs'

type Props = {
  children: ReactNode
  title?: string
  breadcrumbItems?: breadCrumbsitem[]
}

// 全てのコンポーネントを括るコンポーネント
export const Layout: FC<Props> = ({ title, children, breadcrumbItems }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className='rounded-md flex border-2 shadow-md mx-2 mt-2 py-4 px-4 items-center justify-between'>
        <h1 className='text-xl'>
          <Link href='/'>Cypas CMS</Link>
        </h1>
        <nav className='flex gap-3'>
          <Link href='/courses'>コース一覧</Link>
          <Link href='/useragents'>ユーザーエージェント一覧</Link>
        </nav>
      </header>

      <main className='mx-4 py-6'>
        {breadcrumbItems && (
          <div className='mb-4 overflow-x-auto overflow-y-hidden'>
            <BreadCrumbs items={breadcrumbItems} />
          </div>
        )}

        {children}
      </main>
    </>
  )
}
