import Head from 'next/head'
import Link from 'next/link'
import { FC, ReactNode } from 'react'

type Props = {
  children: ReactNode
  title?: string
}

export const Layout: FC<Props> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className='rounded-md flex border-2 shadow-md mx-2 mt-2 py-4 px-4 items-center justify-between'>
        <h1 className='text-xl'>
          <Link href='/'>カリキュラム管理システム</Link>
        </h1>
        <nav className='flex gap-3'>
          <Link href='/courses'>コース一覧</Link>
          <Link href='/curriculums'>カリキュラム一覧</Link>
          <Link href='/useragents'>ユーザーエージェント一覧</Link>
        </nav>
      </header>

      <main className='mx-4 mt-8'>{children}</main>
    </>
  )
}
