import Head from 'next/head'
import Link from 'next/link'
import { FC, ReactNode } from 'react'

type Props = {
  children: ReactNode
  title?: string
}

export const Layout: FC<Props> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className='rounded-md border-2 shadow-md mx-2 mt-2 text-2xl py-4 px-4 flex items-center justify-between'>
        <h1 className='text-xl'>
          <Link href='/'>カリキュラム管理システム</Link>
        </h1>
        <Link href='/page2'>page2</Link>
      </header>

      <main className='mx-4 mt-8'>{children}</main>
    </>
  )
}
