import Link from 'next/link'
import 'windi.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <header className='rounded-md flex border-2 shadow-md mx-2 mt-2 py-4 px-4 text-2xl items-center justify-between'>
          <h1 className='text-xl'>
            <Link href='/'>カリキュラム管理システム</Link>
          </h1>
          <Link href='/about'>about</Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
