import { Anpan } from '@prisma/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useCallback, useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { Sample } from '../components/Sample'
import { CourseList } from '../components/CourseList'
import { CourseItem } from '../components/CourseItem'
import { CurriculumItem } from '../components/CurriculumItem'
import { Relation } from '../components/Relation'

const Home: NextPage = () => {
  const [anpan, setAnpan] = useState<Anpan>()
  const [anpans, setAnpans] = useState<Anpan[]>()
  const [email, setEmail] = useState('')

  // const getAnpan = useCallback(async () => {
  //   try {
  //     const res = await fetch('/api/anpan/1').then(res => res.json())
  //     setAnpan(res.data)
  //     console.log({ res })
  //   } catch (e) {
  //     console.error(e)
  //   }
  // }, [])

  // const getAnpans = useCallback(async () => {
  //   try {
  //     const res = await fetch('/api/anpan').then(res => res.json())
  //     setAnpans(res.data)
  //     console.log({ res })
  //   } catch (e) {
  //     console.error(e)
  //   }
  // }, [])

  // useEffect(() => {
  //   getAnpan()
  //   getAnpans()
  // }, [getAnpan, getAnpans])

  // const createAnpan = useCallback(async (email: string) => {
  //   if (!email) {
  //     console.log('emailが空です！')
  //     return
  //   }

  //   try {
  //     const res = await fetch('/api/anpan', {
  //       method: 'POST',
  //       headers: {
  //         'Content-Type': 'application/json',
  //       },
  //       body: JSON.stringify({
  //         email,
  //         name: 'aa',
  //       }),
  //     }).then(res => res.json())
  //     console.log('追加に成功', res)
  //   } catch (e) {
  //     console.error(e)
  //   }
  // }, [])

  // const updateAnpan = useCallback(async () => {
  //   try {
  //     const res = await fetch('/api/anpan/1', {
  //       method: 'PUT',
  //       headers: {
  //         'Content-Type': 'application/json',
  //       },
  //       body: JSON.stringify({
  //         email: 'emailです',
  //         name: 'test1 update2',
  //       }),
  //     }).then(res => res.json())
  //     console.log('更新に成功', res)
  //   } catch (e) {
  //     console.error(e)
  //   }
  // }, [])

  // const deleteAnpan = useCallback(async () => {
  //   try {
  //     const res = await fetch('/api/anpan/2', {
  //       method: 'DELETE',
  //     }).then(res => res.json())
  //     console.log('削除に成功', res)
  //   } catch (e) {
  //     console.error(e)
  //   }
  // }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ul>
          {anpans?.length &&
            anpans.map((v, i) => (
              <li key={i} style={{ display: 'flex', gap: '5px' }}>
                <p>{v.id}</p>
                <p>{v.email}</p>
                <p>{v.name}</p>
              </li>
            ))}
        </ul>

        <div style={{ wordBreak: 'break-all' }}>
          <CourseList />
          <CourseItem id='clgkj5xv20000n0pgd4o5wslw' />

          <CurriculumItem />

          <Relation />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
