import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useCallback, useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { CourseList } from '../components/CourseList'
import { CourseItem } from '../components/CourseItem'
import { CurriculumItem } from '../components/CurriculumItem'
import { Relation } from '../components/Relation'
import { Course } from '@prisma/client'
import Link from 'next/link'
import { useGetApi } from '../hooks/useApi'

const Home: NextPage = () => {
  const { data: courses } = useGetApi<Course[]>(`/courses`)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div style={{ wordBreak: 'break-all' }}>
          <Link href='/page2'>page2</Link>
          <CourseList />
          {courses?.[0]?.id && <CourseItem id={courses[0].id} />}

          <CurriculumItem />

          <Relation />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
