-- DropForeignKey
ALTER TABLE "Article" DROP CONSTRAINT "Article_sectionId_fkey";

-- DropForeignKey
ALTER TABLE "Quiz" DROP CONSTRAINT "Quiz_sectionId_fkey";

-- DropForeignKey
ALTER TABLE "Section" DROP CONSTRAINT "Section_courseId_fkey";

-- DropForeignKey
ALTER TABLE "Section" DROP CONSTRAINT "Section_userAgentId_fkey";

-- DropIndex
DROP INDEX "UserAgent_name_key";

-- AlterTable
ALTER TABLE "Article" ALTER COLUMN "sectionId" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Course" ALTER COLUMN "name" SET DATA TYPE VARCHAR,
ALTER COLUMN "imageUrl" SET DATA TYPE VARCHAR,
ALTER COLUMN "author" SET DATA TYPE VARCHAR,
ALTER COLUMN "organization" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Quiz" ALTER COLUMN "answer" SET DATA TYPE VARCHAR,
ALTER COLUMN "sectionId" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Scenario" ALTER COLUMN "name" SET DATA TYPE VARCHAR,
ALTER COLUMN "gitHubUrl" SET DATA TYPE VARCHAR,
ALTER COLUMN "author" SET DATA TYPE VARCHAR,
ALTER COLUMN "organization" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Section" ALTER COLUMN "name" SET DATA TYPE VARCHAR,
ALTER COLUMN "type" SET DATA TYPE VARCHAR,
ALTER COLUMN "scenarioGitHubUrl" SET DATA TYPE VARCHAR,
ALTER COLUMN "userAgentId" SET DATA TYPE VARCHAR,
ALTER COLUMN "courseId" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "UserAgent" ALTER COLUMN "name" SET DATA TYPE VARCHAR,
ALTER COLUMN "gitHubUrl" SET DATA TYPE VARCHAR,
ALTER COLUMN "type" SET DATA TYPE VARCHAR,
ALTER COLUMN "author" SET DATA TYPE VARCHAR,
ALTER COLUMN "organization" SET DATA TYPE VARCHAR;

-- AddForeignKey
ALTER TABLE "Section" ADD CONSTRAINT "Section_userAgentId_fkey" FOREIGN KEY ("userAgentId") REFERENCES "UserAgent"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Section" ADD CONSTRAINT "Section_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Article" ADD CONSTRAINT "Article_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Quiz" ADD CONSTRAINT "Quiz_sectionId_fkey" FOREIGN KEY ("sectionId") REFERENCES "Section"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
